// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metadata, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Metadata, error) {
	out := new(Metadata)
	err := c.cc.Invoke(ctx, "/plugins.Plugin/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, "/plugins.Plugin/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility
type PluginServer interface {
	GetMetadata(context.Context, *Empty) (*Metadata, error)
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (UnimplementedPluginServer) GetMetadata(context.Context, *Empty) (*Metadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedPluginServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.Plugin/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).GetMetadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Plugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.Plugin/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _Plugin_GetMetadata_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Plugin_Configure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// SourcePluginClient is the client API for SourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SourcePluginClient interface {
	ReadLogs(ctx context.Context, in *ReadLogsRequest, opts ...grpc.CallOption) (*RawLog, error)
}

type sourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewSourcePluginClient(cc grpc.ClientConnInterface) SourcePluginClient {
	return &sourcePluginClient{cc}
}

func (c *sourcePluginClient) ReadLogs(ctx context.Context, in *ReadLogsRequest, opts ...grpc.CallOption) (*RawLog, error) {
	out := new(RawLog)
	err := c.cc.Invoke(ctx, "/plugins.SourcePlugin/ReadLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourcePluginServer is the server API for SourcePlugin service.
// All implementations must embed UnimplementedSourcePluginServer
// for forward compatibility
type SourcePluginServer interface {
	ReadLogs(context.Context, *ReadLogsRequest) (*RawLog, error)
	mustEmbedUnimplementedSourcePluginServer()
}

// UnimplementedSourcePluginServer must be embedded to have forward compatible implementations.
type UnimplementedSourcePluginServer struct {
}

func (UnimplementedSourcePluginServer) ReadLogs(context.Context, *ReadLogsRequest) (*RawLog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLogs not implemented")
}
func (UnimplementedSourcePluginServer) mustEmbedUnimplementedSourcePluginServer() {}

// UnsafeSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourcePluginServer will
// result in compilation errors.
type UnsafeSourcePluginServer interface {
	mustEmbedUnimplementedSourcePluginServer()
}

func RegisterSourcePluginServer(s grpc.ServiceRegistrar, srv SourcePluginServer) {
	s.RegisterService(&SourcePlugin_ServiceDesc, srv)
}

func _SourcePlugin_ReadLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcePluginServer).ReadLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.SourcePlugin/ReadLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcePluginServer).ReadLogs(ctx, req.(*ReadLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourcePlugin_ServiceDesc is the grpc.ServiceDesc for SourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.SourcePlugin",
	HandlerType: (*SourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadLogs",
			Handler:    _SourcePlugin_ReadLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// ParserPluginClient is the client API for ParserPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParserPluginClient interface {
	ParseLog(ctx context.Context, in *RawLog, opts ...grpc.CallOption) (ParserPlugin_ParseLogClient, error)
}

type parserPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewParserPluginClient(cc grpc.ClientConnInterface) ParserPluginClient {
	return &parserPluginClient{cc}
}

func (c *parserPluginClient) ParseLog(ctx context.Context, in *RawLog, opts ...grpc.CallOption) (ParserPlugin_ParseLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &ParserPlugin_ServiceDesc.Streams[0], "/plugins.ParserPlugin/ParseLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &parserPluginParseLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ParserPlugin_ParseLogClient interface {
	Recv() (*ParsedLog, error)
	grpc.ClientStream
}

type parserPluginParseLogClient struct {
	grpc.ClientStream
}

func (x *parserPluginParseLogClient) Recv() (*ParsedLog, error) {
	m := new(ParsedLog)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ParserPluginServer is the server API for ParserPlugin service.
// All implementations must embed UnimplementedParserPluginServer
// for forward compatibility
type ParserPluginServer interface {
	ParseLog(*RawLog, ParserPlugin_ParseLogServer) error
	mustEmbedUnimplementedParserPluginServer()
}

// UnimplementedParserPluginServer must be embedded to have forward compatible implementations.
type UnimplementedParserPluginServer struct {
}

func (UnimplementedParserPluginServer) ParseLog(*RawLog, ParserPlugin_ParseLogServer) error {
	return status.Errorf(codes.Unimplemented, "method ParseLog not implemented")
}
func (UnimplementedParserPluginServer) mustEmbedUnimplementedParserPluginServer() {}

// UnsafeParserPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserPluginServer will
// result in compilation errors.
type UnsafeParserPluginServer interface {
	mustEmbedUnimplementedParserPluginServer()
}

func RegisterParserPluginServer(s grpc.ServiceRegistrar, srv ParserPluginServer) {
	s.RegisterService(&ParserPlugin_ServiceDesc, srv)
}

func _ParserPlugin_ParseLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RawLog)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParserPluginServer).ParseLog(m, &parserPluginParseLogServer{stream})
}

type ParserPlugin_ParseLogServer interface {
	Send(*ParsedLog) error
	grpc.ServerStream
}

type parserPluginParseLogServer struct {
	grpc.ServerStream
}

func (x *parserPluginParseLogServer) Send(m *ParsedLog) error {
	return x.ServerStream.SendMsg(m)
}

// ParserPlugin_ServiceDesc is the grpc.ServiceDesc for ParserPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.ParserPlugin",
	HandlerType: (*ParserPluginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ParseLog",
			Handler:       _ParserPlugin_ParseLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

// OutputPluginClient is the client API for OutputPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutputPluginClient interface {
	Proc(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error)
}

type outputPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewOutputPluginClient(cc grpc.ClientConnInterface) OutputPluginClient {
	return &outputPluginClient{cc}
}

func (c *outputPluginClient) Proc(ctx context.Context, in *EvaluationRequest, opts ...grpc.CallOption) (*EvaluationResponse, error) {
	out := new(EvaluationResponse)
	err := c.cc.Invoke(ctx, "/plugins.OutputPlugin/Proc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputPluginServer is the server API for OutputPlugin service.
// All implementations must embed UnimplementedOutputPluginServer
// for forward compatibility
type OutputPluginServer interface {
	Proc(context.Context, *EvaluationRequest) (*EvaluationResponse, error)
	mustEmbedUnimplementedOutputPluginServer()
}

// UnimplementedOutputPluginServer must be embedded to have forward compatible implementations.
type UnimplementedOutputPluginServer struct {
}

func (UnimplementedOutputPluginServer) Proc(context.Context, *EvaluationRequest) (*EvaluationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proc not implemented")
}
func (UnimplementedOutputPluginServer) mustEmbedUnimplementedOutputPluginServer() {}

// UnsafeOutputPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutputPluginServer will
// result in compilation errors.
type UnsafeOutputPluginServer interface {
	mustEmbedUnimplementedOutputPluginServer()
}

func RegisterOutputPluginServer(s grpc.ServiceRegistrar, srv OutputPluginServer) {
	s.RegisterService(&OutputPlugin_ServiceDesc, srv)
}

func _OutputPlugin_Proc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputPluginServer).Proc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.OutputPlugin/Proc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputPluginServer).Proc(ctx, req.(*EvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutputPlugin_ServiceDesc is the grpc.ServiceDesc for OutputPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutputPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.OutputPlugin",
	HandlerType: (*OutputPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proc",
			Handler:    _OutputPlugin_Proc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
